# The flowgraphs in this package are generated by GNU Radio Companion from the
# .grc files beside them, so they import the packet library under its bare name.
# Importing challenges.gotenna_packet first registers it under that name.
#from challenges import gotenna_packet  # noqa: F401
