name: Challengectl test

on:
  push:

jobs:
  challengectl-test:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: List added files
      run: git diff-tree --no-commit-id --name-only -r ${{ github.sha }}
    -
      name: challengectl test
      run: |
        sudo ./qa/challengectl-test
