#!/bin/sh
docker pull rfhs/rfctf-sdr
docker run --rm --network none --name "rfhs-rfctf-sdr-ci" \
  --tmpfs "/run:mode=0755,nosuid,nodev,nr_inodes=800k,size=20%,strictatime" \
  -v '.:/root/challengectl' \
  rfhs/rfctf-sdr ./qa/challengectl-test-recursive
